######################################################################
#
# File name : tb_display7_simulate.do
# Created on: Thu Dec 25 11:53:07 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.tb_display7 xil_defaultlib.glbl

do {tb_display7_wave.do}

view wave
view structure
view signals

do {tb_display7.udo}

run 1000ns
