######################################################################
#
# File name : tb_display7_compile.do
# Created on: Thu Dec 25 11:52:59 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelism\\win32pe\\vlib work
D:\\modelism\\win32pe\\vlib msim

D:\\modelism\\win32pe\\vlib msim/xil_defaultlib

D:\\modelism\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\modelism\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../tj_mp3.srcs/sources_1/new/Divider.v" \
"../../../tj_mp3.srcs/sources_1/new/display7.v" \
"../../../tj_mp3.srcs/sim_1/new/display7_tb.v" \


# compile glbl module
D:\\modelism\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

