######################################################################
#
# File name : tb_display7_wave.do
# Created on: Thu Dec 25 11:53:07 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
