# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/modelism/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/vivadotest/tj_mp3/tj_mp3/tj_mp3.cache/wt [current_project]
set_property parent.project_path F:/vivadotest/tj_mp3/tj_mp3/tj_mp3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  F:/vivadotest/tj_mp3/tj_mp3/tj_mp3.srcs/sources_1/new/Divider.v
  F:/vivadotest/tj_mp3/tj_mp3/tj_mp3.srcs/sources_1/new/timeCounter.v
  F:/vivadotest/tj_mp3/tj_mp3/tj_mp3.srcs/sources_1/new/display7.v
  F:/vivadotest/tj_mp3/tj_mp3/tj_mp3.srcs/sources_1/new/Top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/vivadotest/tj_mp3/tj_mp3/tj_mp3.srcs/constrs_1/new/Setting.xdc
set_property used_in_implementation false [get_files F:/vivadotest/tj_mp3/tj_mp3/tj_mp3.srcs/constrs_1/new/Setting.xdc]


synth_design -top system_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef system_top.dcp

catch { report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb }
