set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN E3 [get_ports CLK]
set_property -dict { PACKAGE_PIN J15 IOSTANDARD LVCMOS33 } [get_ports { RST }];
set_property -dict { PACKAGE_PIN P17 IOSTANDARD LVCMOS33 } [get_ports { BTNL }];
set_property -dict { PACKAGE_PIN N17 IOSTANDARD LVCMOS33 } [get_ports { BTNC }];
set_property -dict { PACKAGE_PIN M17 IOSTANDARD LVCMOS33 } [get_ports { BTNR }];
set_property -dict { PACKAGE_PIN M18 IOSTANDARD LVCMOS33 } [get_ports { BTND }];
set_property -dict { PACKAGE_PIN P18 IOSTANDARD LVCMOS33 } [get_ports { BTNU }];
set_property IOSTANDARD LVCMOS33 [get_ports {SHIFT[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHIFT[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHIFT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHIFT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHIFT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHIFT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHIFT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHIFT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DOT]
set_property PACKAGE_PIN H15 [get_ports DOT]
set_property PACKAGE_PIN U13 [get_ports {SHIFT[7]}]
set_property PACKAGE_PIN K2 [get_ports {SHIFT[6]}]
set_property PACKAGE_PIN T14 [get_ports {SHIFT[5]}]
set_property PACKAGE_PIN P14 [get_ports {SHIFT[4]}]
set_property PACKAGE_PIN J14 [get_ports {SHIFT[3]}]
set_property PACKAGE_PIN T9 [get_ports {SHIFT[2]}]
set_property PACKAGE_PIN J18 [get_ports {SHIFT[1]}]
set_property PACKAGE_PIN J17 [get_ports {SHIFT[0]}]
set_property PACKAGE_PIN L18 [get_ports {SEG[6]}]
set_property PACKAGE_PIN T11 [get_ports {SEG[5]}]
set_property PACKAGE_PIN P15 [get_ports {SEG[4]}]
set_property PACKAGE_PIN K13 [get_ports {SEG[3]}]
set_property PACKAGE_PIN K16 [get_ports {SEG[2]}]
set_property PACKAGE_PIN R10 [get_ports {SEG[1]}]
set_property PACKAGE_PIN T10 [get_ports {SEG[0]}]